version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

commands:
  diagnose:
    steps:
      - run: docker version
      - run: docker info
      - run: docker system info

jobs:
  build_image:
    machine:
      image: "ubuntu-2004:202107-02"
      docker_layer_caching: true
    environment:
      AWS_ECR_REGISTRY_ID: '123456789012'
      AWS_REGION: 'ap-northeast-1'
    steps:
      - checkout
      - diagnose
      - aws-ecr/build-image:
          platform: linux/amd64,linux/arm64
          repo: kelvintaywlcircleci/fancy-nginx-xplatform
          tag: latest
          extra-build-args: |
            --progress plain

workflows:
  main:
    jobs:
      - build_image
